[package]
name = "spine-atlas-cutter"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }
clio = { version = "0.3.5", features = ["clap", "clap-parse"] }
derive_builder = "0.20.0"
image = "0.24.9"
regex = "1.10.3"